In [ ]:
import pandas as pd
print ("library imported successfully")

library imported successfully

In [ ]:
df = pd.read_csv('student_performance.csv')

In [ ]:
print("Dataset loaded successfully")

Dataset loaded successfully

To view the last 5 rows

In [ ]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
print("Shape of dataset : ", df.shape)
#shape is an attribute of a dataform
#it returns the tuple (pair of numbers) : (number_of_rows, nuo_of_columns)
#ex : (30, 13)  means 30 rows and 13 columns

Shape of dataset :  (30, 13)

In [ ]:
print("Number of students : ", df.shape[0])

Number of students :  30

In [ ]:
print("columns in the dataset: ")
print(df.columns.tolist())

#.columns gives us all column names
#.tolist converts is from pandas index object into a regular python list

columns in the dataset:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [ ]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [ ]:
print ("Data type : ", df.dtypes)

Data type :  student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
print("Missing value in each column : ")
print(df.isnull().sum())

Missing value in each column :
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [ ]:
print("\nTotal missing values : " , df.isnull().sum().sum())

Total missing values :  0

In [ ]:
print("Student Names :")
print(df['name'])

Student Names :
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [ ]:
print("Departments in this dataset : ")
print(df['department'].unique())
()

Departments in this dataset :
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [ ]:
print("\nHow many students per department : ")
print(df['department'].value_counts())

How many students per department :
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
cse_students = df[df['department'] == 'computer Science']
print(f"Number of Computer Science Enginnering students : {len(cse_students)}")

Number of Computer Science Enginnering students : 0

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('student_performance.csv')

In [ ]:
high_attendance = df[df['attendance_percentage'] > 90]

print(f"Students with attendance above 90% : {len(high_attendance)}")

Students with attendance above 90% : 10

In [ ]:
cs_students =df[df['department'] == 'Computer Science']
print(f"print length:", len(cs_students))

print length: 13

In [ ]:
df['total_score']=df['math_score']+df['science_score']+df['programming_score']+df['english_score']

top_student=df.loc[df['total_score'].idxmax()]

print("Top student : ")
print(f"Name : {top_student['name']}")
print(f"Department : {top_student['department']}")
print(f"Total Score : {top_student['total_score']}")
print(f"Attendance : {top_student['attendance_percentage']}")

Top student :
Name : Ananya Das
Department : Computer Science
Total Score : 371
Attendance : 98

In [ ]:
#group by func
dept_avg = df.groupby('department')['total_score'].mean().round(2)
print("Average Total Score by each Dept:")
print(dept_avg)

Average Total Score by each Dept:
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [ ]:
#sorting
#ascending -> false bcoz no fun in python for desc
df_sorted=df.sort_values(by='total_score',ascending=False)
print("top 10 student:")
print(df_sorted[['name','department','total_score','attendance_percentage']].head(10))

top 10 student:
              name        department  total_score  attendance_percentage
9       Ananya Das  Computer Science          371                     98
21     Tanvi Mehta  Computer Science          367                     97
29  Akanksha Yadav  Computer Science          365                     95
4       Arjun Nair  Computer Science          356                     90
7      Divya Singh  Computer Science          356                     96
17  Swati Kulkarni  Computer Science          354                     94
24       Amit Bose  Computer Science          336                     91
12      Suresh Rao  Computer Science          334                     88
19    Nisha Kapoor  Computer Science          327                     89
0     Aarav Sharma  Computer Science          326                     92

In [ ]:
                                                                   # PRACTICE QUESTIONS


import pandas as pd
df = pd.read_csv('student_performance.csv')
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
electronics_count = df[df['department'] == 'Electronics'].shape[0]
print("Electronics Department Students:", electronics_count)

Electronics Department Students: 6

In [ ]:
female_attendance_avg = df[df['gender'] == 'Female']['attendance_percentage'].mean()
print("Average Attendance of Female Students:", female_attendance_avg)

Average Attendance of Female Students: 88.53333333333333

In [ ]:
lowest_programming = df.loc[df['programming_score'].idxmin()]
print("Student with Lowest Programming Score:")
print(lowest_programming[['name', 'department', 'programming_score']])

Student with Lowest Programming Score:
name                 Manoj Pandey
department                  Civil
programming_score              38
Name: 16, dtype: object

In [ ]:
math_above_80 = df[df['math_score'] > 80].shape[0]
print("Students scoring above 80 in Math:", math_above_80)

Students scoring above 80 in Math: 11

In [ ]:
df['total_score']=df['math_score']+df['science_score']+df['programming_score']+df['english_score']

In [ ]:
high_attendance_avg = df[df['attendance_percentage'] > 90]['total_score'].mean()
print("Average Total Score (Attendance > 90%):", high_attendance_avg)

Average Total Score (Attendance > 90%): 335.8